token = "bot_token"  # The token for the bot.
is_base64 = false # If the bot token is base64 encoded.
sudo_enabled = false
pubkey = "bot_interaction_pubkey"  # The HTTP interactions pubkey for your bot.
owners = []  # List of owner IDs - these people override all permission checks.
dm_uncaught_errors = true  # Whether or not to DM the owners when unhandled errors are encountered.
user_agent = ""  # A custom string to populate Bot.user_agent with.
guild_settings_prefix_column = "prefix"  # Used if multiple bots connect to the same database and need to seperate their prefixes.
ephemeral_error_messages = true  # Whether or not error messages [from slash commands] should be ephemeral.
owners_ignore_check_failures = true  # Whether or not owners ignore check failures on messages.

# These are used with the on_message event. As such, they will likely soon be deprecated.
default_prefix = ">"  # The prefix for the bot's commands.
cached_messages = 1000  # The number of messages to cache within the bot.

# The intents that the bot should start with
[intents]
    guilds = true  # Guilds - Used for guild join/remove, channel create/delete/update, Bot.get_channel, Bot.guilds, Bot.get_guild. This is REALLY needed.
    members = true  # Members (privileged intent) - Used for member join/remove/update, Member.roles, Member.nick, User.name, Bot.get_user, Guild.get_member etc.
    bans = false  # Bans - Used for member ban/unban.
    emojis = true  # Emojis - Used for guild emojis update, Bot.get_emoji, Guild.emojis.
    integrations = true  # Integrations - Used for guild integrations update.
    webhooks = false  # Webhooks - Used for guild webhooks update.
    invites = true # Invites - Used for invite create/delete.
    voice_states = false  # Voice states - Used for voice state update, VoiceChannel.members, Member.voice.
    presences = false  # Presences (privileged intent) - Used for member update (for activities and status), Member.status.
    guild_messages = true  # Guild messages (privileged intent) - Used for message events in guilds.
    dm_messages = true # DM messages (privileged intent) - Used for message events in DMs.
    guild_reactions = false  # Guild reactions - Used for [raw] reaction add/remove/clear events in guilds.
    dm_reactions = false  # DM reactions - Used for [raw] reaction add/remove/clear events in DMs.
    guild_typing = false  # Guild typing - Used for the typing event in guilds.
    dm_typing = false  # DM typing - Used for the typing event in DMs.
    message_content = true  # Message content (privileged intent) - Whether or not you get message content.

# The info command is the slash command equivelant of "help", giving all relevant data.
[bot_info]
    enabled = true
    include_stats = true
    content = """
    idk what to put here
    """
    thumbnail = ""  # A url to an image to be added to the embed
    image = ""  # A url to an image to be added to the embed

    # These are added as link buttons the bottom of the message.
    # Your bot invite (if enabled) will always be added as the first button.
    [bot_info.links.Git]
        url = "https://github.com/6days9weeks/join-gate-bot"

# Used to generate the invite link.
[oauth]
    enabled = false  # Whether or not an invite link is enabled via the !invite command.
    response_type = ""  # The response type given to the redirect URI.
    redirect_uri = ""  # Where the user should be redirected to upon authorizing.
    client_id = ""  #  If not set then will use the bot's ID.
    scope = "bot applications.commands"  # The scope that will be generated with the invite link, space seperated (applications.commands for slash).
    permissions = []  # args here are passed directly to discord.Permissions as True.

# Data needed for SQL database connections
[database]
    type = "sqlite"  # postgres, sqlite, mysql
    enabled = true
    user = ""
    password = ""
    database = ".database.sqlite"
    host = "127.0.0.1"
    port = 5432

# The data that gets shoves into custom context for the embed.
[embed]
    enabled = false  # Whether or not to embed messages by default.
    content = ""  # Default content to be added to the embed message.
    colour = 0  # A specific colour for the embed - 0 means random.
    [embed.author]
        enabled = false
        name = "{ctx.bot.user}"
        url = ""  # The url added to the author.
    [[embed.footer]]  # An array of possible footers.
        text = "Add the bot to your server! ({ctx.clean_prefix}invite)"  # Text to appear in the footer.
        amount = 1  # The amount of times this particular text is added to the pool.

# What the bot is playing
[presence]
    activity_type = "playing"  # Should be one of 'playing', 'listening', 'watching', 'competing'
    text = ""
    status = "online"  # Should be one of 'online', 'invisible', 'idle', 'dnd'
    include_shard_id = true  # Whether or not to append "(shard N)" to the presence text; only present if there's more than 1 shard
